import Link from 'next/link';
import { notFound } from 'next/navigation';
import HotelImage from '@/components/HotelImage';
const rooms: Record<string,{name:string;image:string;bed:string;guests:string;size:string;desc:string}> = {
 standard:{name:'Standard Room',image:'/images/standard-room.jpg',bed:'1 double bed',guests:'XXXX guests',size:'XXXX m²',desc:'A calm, comfortable room designed for restful stays with thoughtful essentials.'},
 deluxe:{name:'Deluxe Room',image:'/images/deluxe-room.jpg',bed:'1 king bed',guests:'XXXX guests',size:'XXXX m²',desc:'A spacious room with an elevated sense of comfort for business or leisure.'},
 executive:{name:'Executive Room',image:'/images/executive-room.jpg',bed:'1 king bed',guests:'XXXX guests',size:'XXXX m²',desc:'A polished stay with space to work, unwind and settle in.'},
 family:{name:'Family Room',image:'/images/family-room.jpg',bed:'Family configuration',guests:'XXXX guests',size:'XXXX m²',desc:'Flexible accommodation for families and groups travelling together.'},
 suite:{name:'Suite',image:'/images/suite.jpg',bed:'XXXX',guests:'XXXX guests',size:'XXXX m²',desc:'A generously arranged suite for guests who value extra room and privacy.'},
};
export function generateStaticParams(){return Object.keys(rooms).map(slug=>({slug}))}
export default async function RoomPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const r=rooms[slug];if(!r)notFound();return <main className="max-w-7xl mx-auto px-4 py-12 sm:py-20"><Link href="/rooms" className="text-red-700 text-sm font-bold">← All rooms</Link><div className="grid lg:grid-cols-2 gap-10 mt-6 items-center"><div className="relative h-[360px] sm:h-[520px] rounded-3xl overflow-hidden"><HotelImage src={r.image} alt={r.name} fill className="object-cover" /></div><div><p className="text-red-700 uppercase tracking-[.25em] text-xs font-bold">SDL accommodation</p><h1 className="text-5xl sm:text-6xl font-bold mt-3">{r.name}</h1><p className="text-gray-600 text-lg leading-relaxed mt-5">{r.desc}</p><div className="grid grid-cols-2 gap-3 my-8">{[['Bed type',r.bed],['Guests',r.guests],['Room size',r.size],['Bathroom','Private bathroom'],['Air conditioning','Included'],['Wi-Fi','Available'],['Television','Included'],['Price per night','XXXX ZMW']].map(([a,b])=><div className="border border-gray-200 p-4 rounded-xl" key={a}><p className="text-xs text-gray-500 uppercase">{a}</p><p className="font-semibold mt-1">{b}</p></div>)}</div><Link href="/contact#booking" className="inline-block px-7 py-4 rounded-xl gold-btn">BOOK THIS ROOM</Link></div></div></main>}
